In [3]:
# 데이터 전처리 연습(nan으로 누락된 결측치들을 평균값으로 재정의 해보기)용 실습 코드
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 

In [8]:
dataset = pd.read_csv('/content/sample_data/DataPreprocessing.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [11]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [13]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X=LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [15]:
from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler()
X = minmax_scaler.fit_transform(X)
print(X) #Place for scale

[[0.5        0.73913043 0.68571429]
 [0.         0.         0.        ]
 [1.         0.13043478 0.17142857]
 [0.         0.47826087 0.37142857]
 [1.         0.56521739 0.45079365]
 [0.5        0.34782609 0.28571429]
 [0.         0.51207729 0.11428571]
 [0.5        0.91304348 0.88571429]
 [1.         1.         1.        ]
 [0.5        0.43478261 0.54285714]]


In [14]:
X

array([[1, 49.0, 86400.0],
       [0, 32.0, 57600.0],
       [2, 35.0, 64800.0],
       [0, 43.0, 73200.0],
       [2, 45.0, 76533.33333333333],
       [1, 40.0, 69600.0],
       [0, 43.77777777777778, 62400.0],
       [1, 53.0, 94800.0],
       [2, 55.0, 99600.0],
       [1, 42.0, 80400.0]], dtype=object)

In [10]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)